name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test

      - name: Run linting
        run: pnpm run lint

      - name: Build project
        run: pnpm run build

      - name: Verify build output
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "Build failed - dist/index.js not found"
            exit 1
          fi
          if [ ! -f "dist/cli/index.js" ]; then
            echo "Build failed - dist/cli/index.js not found"
            exit 1
          fi

      - name: Prepare packages
        run: pnpm run prepublish-all
        env:
          TAG_NAME: ${{ github.ref_name }}

      - name: Commit release
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Release Version ${{ github.ref_name }} [skip ci]
          branch: main
          push_options: --force

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}